baseURL = 'https://twistors105.github.io/'
languageCode = 'en-us'
title = "twistors105"
theme = ['smol', 'hugo-cite']
capitalizeListTitles = 'false'

[taxonomies]
   tag = "tags"
   category = "categories"

# Parameters
[params]
    subtitle = "a research weblog"
    dateFmt = "02.01.2006 15:04"
    math = true

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts/"
        title = "posts"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = 4
# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/twistors105"
        weight = 1 


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
